### ISSUE TITLE
Question: What is the flag to use integer simple.

### ISSUE THREAD

**Issue by pjljvandelaar** [RyanGlScott/text-show#31]
On windows, the usage of integer-gmp package is problematic (see e.g. https://github.com/commercialhaskell/stack/issues/399).
Most packages therefore offer a flag to use the alternative integer-simple package.
For example:
```
  text: 
    integer-simple: true
  hashable:
    integer-gmp: false
  integer-logarithms:
    integer-gmp: false
  scientific:
    integer-simple: true
```
Unfortunately, the flag is not standardized...
In the documentation on https://hackage.haskell.org/package/text-show, I can't find how this flag is named in test-show.
So my question: how is the flag to use integer-simple instead of integer-gmp called in text-show?
